### ISSUE TITLE
[CSSWG][FXTF] CR transition for css-transforms-1

### ISSUE THREAD

**Issue by dirkschulze** [w3c/transitions#106]
# CSS Transforms Module Level 1, Nov 20th 2018
https://www.w3.org/TR/css-transforms-1/
https://drafts.csswg.org/css-transforms-1/

# Abstract
CSS transforms allows elements styled with CSS to be transformed in two-dimensional space. This specification is the convergence of the CSS 2D transforms and SVG transforms specifications.

# Status
Previous publication: 
https://www.w3.org/TR/2017/WD-css-transforms-1-20171130/ as WD

# Link to group's decision to request transition
https://www.w3.org/2018/07/03-fx-minutes.html#item03

# Changes
Changes since last publication: https://drafts.csswg.org/css-transforms-1/#changes
* Added Privacy/Security section.
* Syntax on transform SVG attribute differs to CSS transform syntax.
* Added additional keywords to `transform-box`.
* Smarter interpolation of truncated transform lists

# Requirements satisfied
* All issues closed and either accepted or approved by WG. https://github.com/w3c/csswg-drafts/issues?utf8=✓&q=is%3Aissue+label%3Acss-transforms-1+

# Dependencies met (or not)
* Normatively referenced specifications are in CR. No substantial changes expected.

# Wide Review
https://github.com/w3c/csswg-drafts/issues?utf8=✓&q=is%3Aissue+label%3Acss-transforms-1+

# Issues addressed
https://github.com/w3c/csswg-drafts/issues?utf8=✓&q=is%3Aissue+label%3Acss-transforms-1+

# Formal Objections
None.

# Implementation
* We have mostly interoperable implementations already.
* Many tests written and actively running in browsers.
* 3 months period

# Patent disclosures
???

**Comment by dirkschulze** [comment]
CC @svgeesus

**Comment by plehegar** [comment]
For Patent Disclosures, see https://www.w3.org/2004/01/pp-impl/32061/status#disclosures . If I interpret things properly: we do have disclosures but nothing was excluded.

**Comment by swickr** [comment]
It appears there are new features in this editors' draft that haven't yet been published on /TR.   Please publish a new Working Draft for review.  Please also then explicitly ask for privacy review on [public-privacy](public-privacy@w3.org) and security review on [public-web-security](public-web-security@w3.org).

**Comment by dirkschulze** [comment]
@swickr As far as I understood, there is no need for a spec in CR to go back to a WD anymore especially w/o a LCWD. I do not understand the request.

I updated the link to CSS 2D Transforms to the FPWD.

**Comment by dirkschulze** [comment]
To the request of privacy and security review. Nothing has changed that would affect the privacy and security requirements that have been defined in the spec for multiple WD versions now. We have interoperable behavior of the changed spec parts. Newly defined features are implemented by 2 browsers at least. All other changes are reflecting the already implemented interoperable behavior. (Spec changed to reflect practical reality.) The actual changes since the last WD publication are minimal.
Finally, we have a WG resolution to publish a CR after multiple review passes for a spec that has mostly interoperable implementations.

**Comment by plehegar** [comment]
The reason to request an update as a WD (it's currently a WD, so this is going back from CR to WD) is because the new draft introduces 2 new values for one of the properties, and it's not clear those got the proper attention (they're not documented on MDN for example). So, the recommendation is to publish a WD and request again to move to CR in a month or so. Sending emails for security and privacy checks would also be appropriate (but yes, you may not get additional feedback on those 2 fronts).

**Comment by fantasai** [comment]
OK, it's been two months. No issues have been filed on this spec. Can we transition to CR yet?

**Comment by svgeesus** [comment]
The current ED does not list changes since the previous WD. But that is easy to add, since [there are none](https://github.com/w3c/csswg-drafts/commits/master/css-transforms-1/Overview.bs).

I just spent some hours manually running the test suite. [Initial results](https://test.csswg.org/harness/results/css-transforms-1_dev/grouped/) are very poor:

> 398 of 962 required tests meet CR exit criteria.
> 564 required tests are considered valid and do not meet CR exit criteria.
> 0 required tests have blocking failures.
> 564 required tests might pass but lack data.

> Additional results needed from:
>    Presto: 564
>    Trident: 564
>    WebKit: 513

(I don't have an iOS or OSX device available to run Safari)

However, the poor results can be largely explained by the test suite badly needing maintenance to align it with the specification. For example, there are still some 3D transform tests (should be re-labelled to css-transforms-2) and some tests depend on css-regions-1, which is problematic. The main thing tough is that there are a *ton* of tests for css presentation attributes with units. Nicely written, detailed, well documented, and no longer corresponding to the actual spec. For example

> Test 207 of 962: “SVG presentation attribute and translation-value negative argument with millimeter unit in scientific notation with a negative exponent on translateY”

These should be stashed somewhere in case we ever add back that capability, because these tests represent a lot of work, but also no browser passes them and the spec no longer requires this.

These issues should not prevent the spec *entering* CR, though they would prevent it *exiting*. However, a review of these test failures would be helpful to identify any features at risk. For example section 10: The Transform Function Lists looks risky.

**Comment by svgeesus** [comment]
I raised [an issue on WPT spec maintenance](https://github.com/w3c/csswg-drafts/issues/3637) to track that.

I [added the missing changes section](https://github.com/w3c/csswg-drafts/commit/dde6ea4c7672332154dd7c5a54d66cdf3ee48aa4) noting no substantive change since the Nov 2018 WD

**Comment by svgeesus** [comment]
> ~~ For example section 10: The Transform Function Lists looks risky.~~

It is mainly testing syntax that has now been removed from the spec on the grounds that no browser implements it. On reflection, after reading some of those tests, I'm not seeing at-risk in that section. Just a need to delete/update tests.

**Comment by plehegar** [comment]
Patent Disclosures status: https://www.w3.org/2004/01/pp-impl/32061/status

**Comment by swickr** [comment]
Transition approved.

I assume the usual CSS CR exit criteria will be included in the /TR

**Comment by svgeesus** [comment]
Publication request sent 11 Feb. Expected publication 12 Feb.

**Comment by svgeesus** [comment]
[Published 14 Feb 2019](https://www.w3.org/TR/2019/CR-css-transforms-1-20190214/)
