### ISSUE TITLE
REC Request for HTML Review Draft — Published 29 January 2020

### ISSUE THREAD

**Issue by siusin** [w3c/transitions#308]
# Link to internal transition

https://lists.w3.org/Archives/Team/w3t-comm/2021Jan/0185.html

# Link to previous transition

https://github.com/w3c/transitions/issues/297

**Comment by plehegar** [comment]
https://github.com/w3c/htmlwg/issues

**Comment by swickr** [comment]
Process 2001 requires a record of the Working Group's decision [[6.2.10](https://www.w3.org/2020/Process-20200915/#transition-rec) -> [6.2.3](https://www.w3.org/2020/Process-20200915/#transition-reqs)]. Where may we find that record?

Considering the AC review comments requesting that we provide more description of the changes, we should add this information to the SoTD for future Proposed Recommendations.  In this instance I suggest including in the next AC announcement email the [list of commits](https://github.com/w3c/htmlwg/issues/8#issue-597865240) that the WG had prepared for the Wide Review request so that there is a breadcrumb.

**Comment by plehegar** [comment]
For the Group decision, we can reuse the decision to move to PR (see https://github.com/w3c/w3process/issues/496 )

**Comment by siusin** [comment]
@plehegar @swickr 
Regarding the Non-Recommendations in the [MoU](https://www.w3.org/2019/04/WHATWG-W3C-MOU.html), could you help clarify the status of the superseded documents?
* [The WebSocket API](https://www.w3.org/TR/websockets/) , CR to Rescinded CR, or CR to WG Note?
* [HTML Canvas 2D Context Level 2](https://www.w3.org/TR/2dcontext2/), WG Note -> a new WG Note or leave it as it is?
* [HTML Microdata](https://www.w3.org/TR/microdata/), WD to WG Note?
* [Web Workers](https://www.w3.org/TR/workers/), WD to WG Note?
* [HTML 5.3](https://www.w3.org/TR/html53/), WD to WG Note?

Thank you.

**Comment by swickr** [comment]
@siusin Thanks for the question.  W3C is discontinuing work on those five documents as the material is now superseded by the HTML living standard.  The final status for all five should be WG Note.  The Webhuman may also decide to label them as "retired".

I don't think HTML Canvas 2D L2 needs to be republished; it can just be labeled "retired", especially as its SoTD already contains a prominent comment.

For the other four documents it is appropriate to republish them with a sentence or two in the SoTD explaining that the work is now part of the HTML living standard and no further work on this specific document is planned.

**Comment by siusin** [comment]
Done -> https://lists.w3.org/Archives/Member/w3c-ac-members/2021JanMar/0013.html
