### ISSUE TITLE
FPWD Request for EPUB Accessibility 1.1

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#314]
# Document title, URLs, estimated publication date

- EPUB Accessibility 1.1
    - https://w3c.github.io/epub-specs/epub33/a11y/
    - short name: epub-a11y-11

Publications are planned beginning of 23 February 2021.

# Abstract

- https://w3c.github.io/epub-specs/epub33/a11y/#abstract

# Status

- https://w3c.github.io/epub-specs/epub33/a11y/#sotd

# Is it a delta specification intended to become a W3C Recommendation?

no

# Link to group's decision to request transition

- https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-12-epub#resolution1

# Information about implementations known to the Working Group

This document is based of an earlier, IDPF document, as well as of an ISO document, which are widely followed by the industry already.

Cc: @wareid @mattgarrish @shiestyle @avneeshsingh

**Comment by plehegar** [comment]
Is there a reason to reference WCAG 2.0 instead of 2.1 ?

**Comment by iherman** [comment]
@mattgarrish or @avneeshsingh can you answer the question above?

**Comment by avneeshsingh** [comment]
@plehegar 
EPUB accessibility 1.1 recommends latest version of WCAG. Version 2.0 is the minimum requirement. It is mainly due to backward compatibility because publications are released like products and are not updated like websites.

I am copying the relevant part of specification below:
3.3.1 WCAG Conformance Requirements
An EPUB Publication has to meet the following requirements to conform to this specification:

  It MUST meet the requirements of WCAG 2.0 [WCAG20], but it is strongly RECOMMENDED that it conform to the latest recommended version.

  It MUST meet the requirements of Level A, but it is strongly RECOMMENDED that it meet Level AA [WCAG20].

The reporting flexibility offered by these requirements is to ensure that this specification can be adapted for use wherever accessibility is mandated but without negating or superseding the requirements in effect in any region.

The baseline requirement for WCAG 2.0 Level A, for example, is primarily intended to provide Authors backwards compatibility for older content and flexibility to encourage adoption of accessible production where no formal requirements exist. It is not generally recognized as providing a high degree of accessibility.

Ideally, Authors should try to conform to the latest version of WCAG at Level AA, but the formal thresholds they must meet will be defined by local and national laws, or by procurer or distributor requirements.


https://w3c.github.io/epub-specs/epub33/a11y/index.html#sec-wcag-conf

**Comment by mattgarrish** [comment]
I believe we can fix this now, at least in terms of the general references.

@avneeshsingh has pointed out why we're keeping 2.0 as the baseline, but there now appears to be a redirect on TR/WCAG2 to the latest version so I can add an undated reference to our local biblio.

I think it would be best for our linking to go to the latest version of WCAG even if we keep 2.0 for the baseline.

Does this work for both of you @plehegar and @avneeshsingh ?

**Comment by iherman** [comment]
@plehegar the document has been updated as mentioned in https://github.com/w3c/transitions/issues/314#issuecomment-782036386. Is it o.k. to go ahead and send a publication request?

**Comment by plehegar** [comment]
Both @avneeshsingh and @mattgarrish proposal works for me.

Approved.

**Comment by iherman** [comment]
Published on 2020.02.23, see

https://www.w3.org/blog/news/archives/8923
