### ISSUE TITLE
CR Snapshot Update Request for TTML2 2nd Edition

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#316]
# Document URLs
Timed Text Markup Language 2 (TTML2) (2nd Edition)
https://www.w3.org/TR/2020/CR-ttml2-20200128/ (the latest CR, /ttml2/ points the latest REC)
(targeting) Tue 9 March

# Link to group's decision to request transition
https://www.w3.org/2021/02/04-tt-minutes.html#t05
resolution after two weeks: https://www.w3.org/2021/02/18-tt-minutes.html#t02

# Link to previous Candidate Recommendation transition or update request
https://github.com/w3c/transitions/issues/208

# Substantive changes
no substantive change
change history (in built package): https://github.com/w3c/ttml2/blob/4fde3ab04ec4f16b40d627dfc34ed35423d7b9d6/ttml2-changes.html#L132

# Any changes in requirements?
None

# Wide Review of substantive changes
No substantive change

# Issues status
Nothing substantive open.
https://github.com/w3c/ttml2/milestone/10

# Formal Objections
None

# Any changes in implementation information?
Updated format to add links to show which tests are relevant to which items
https://www.w3.org/wiki/TimedText/TTML2SecondEditionImplementationReport

# Deadline for further comments
28 days as normal

# Any changes in patent disclosures?
None

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by himorin** [comment]
package updated, passed [pubrules](https://www.w3.org/pubrules/?url=https%3A%2F%2Fttml-w3c.himor.in%2Fttml2-CR-20210309%2F&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020) (note: previous and latest differs, that /TR/<shortname>/ points to the latest REC) and [link checker](https://validator.w3.org/checklink?uri=https%3A%2F%2Fttml-w3c.himor.in%2Fttml2-CR-20210309%2F&hide_type=all&depth=&check=Check), and will update date and deadline for publication.
Adding awaiting director label.

**Comment by swickr** [comment]
There are no substantive changes therefore per Process 2020 you may simply [publish a CR Draft](https://www.w3.org/2020/Process-20200915/#publishing-crud).  If you do wish to publish a new CR Snapshot you may do so.

Please don't forget to obtain horizontal review sign-off on the[ "needs resolution" issues that are still open](https://www.w3.org/PM/horizontal/review.html?shortname=ttml) before requesting transition to Proposed Recommendation.

**Comment by nigelmegitt** [comment]
Thanks @swickr the TTWG discussed this: the minutes at https://www.w3.org/2021/02/18-tt-minutes.html#t02 don't make it super clear but as Chair my conclusion was that we were agreeing to publish a CRS, since we want to be able to move to PR as soon as the implementation report allows, and currently there are no other changes that I expect us to roll into a future CRD or CRS.

Good to know we have approval to do either. And thanks for the HR review link - I don't think I was aware of that rather useful tool before. One thing to note is that several of the issues raised are for a future edition or version of TTML, and do not need to be addressed in TTML2 2nd Ed, but they still show up on the tool. Conversely some of the issues do need group consideration, so the reminder is well noted.

**Comment by himorin** [comment]
published
https://www.w3.org/TR/2021/CR-ttml2-20210309/
