### ISSUE TITLE
FPWD Request for Geolocation API

### ISSUE THREAD

**Issue by xfq** [w3c/transitions#331]
# Document title, URLs, estimated publication date
Geolocation API
https://xfq.github.io/testing/geolocation-WD/Overview.html
First Tuesday/Thursday after approval.

# Abstract
https://xfq.github.io/testing/geolocation-WD/Overview.html#abstract

# Status
https://xfq.github.io/testing/geolocation-WD/Overview.html#sotd

# Is it a delta specification intended to become a W3C Recommendation?
No.

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-device-apis/2021Apr/0014.html

# Information about implementations known to the Working Group
https://www.w3.org/2008/geolocation/drafts/API/Implementation-Report.html

**Comment by plehegar** [comment]
Approved

**Comment by deniak** [comment]
The shortname `geolocation-API` is already [used](https://www.w3.org/TR/2016/REC-geolocation-API-20161108/) and since we are relying on shortnames to identify specifications, we cannot re-use them.

It seems it would make sense to publish a CR from the existing REC at this point but looking at the [group discussion](https://github.com/w3c/geolocation-api/issues/42) it doesn't seem possible because of the new features (I understand it would have been possible if the PR/REC were published under the process 2020).
So if the only option is to publish a FPWD, then a new shortname should be used. We'll make sure the specifications are part of the same series even if it's not a versioned shortname.

**Comment by marcoscaceres** [comment]
@deniak, could we use "geolocation" as the new short name?

**Comment by deniak** [comment]
> @deniak, could we use "geolocation" as the new short name?

yes, that one is free if @plehegar approves it.

On a side note, what is the expectation for https://www.w3.org/TR/2016/REC-geolocation-API-20161108/ ? Will it become a superseded REC as soon as the new document reaches CR?

**Comment by marcoscaceres** [comment]
>On a side note, what is the expectation for https://www.w3.org/TR/2016/REC-geolocation-API-20161108/ ? Will it become a superseded REC as soon as the new document reaches CR?

Yes, that's the plan.

**Comment by plehegar** [comment]
ok to use geolocation

**Comment by xfq** [comment]
Published: https://www.w3.org/TR/2021/WD-geolocation-20210527/
