### ISSUE TITLE
CR Snapshot Update Request for CSS Counter Styles Level 3 [css-counter-styles-3]

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#353]
# Document URLs
https://drafts.csswg.org/css-counter-styles-3/
https://www.w3.org/TR/css-counter-styles-3/

# Link to group's decision to request transition
https://www.w3.org/2021/07/14-css-minutes.html#t03

# Link to previous Candidate Recommendation transition or update request
https://github.com/w3c/transitions/issues/23

# Substantive changes
https://drafts.csswg.org/css-counter-styles-3/#changes

# Any changes in requirements?
None

# Wide Review of substantive changes
https://drafts.csswg.org/css-counter-styles-3/issues-cr-2017
(There is one open issue, where we've asked the commenter for more info, but haven't received a response. We're leaving it open.)

Wrt Horizontal Review, we asked for and received review from i18n and a11y. The changes didn't seem relevant to the other groups, so we didn't want to waste their time by asking for formal review, and are hereby submitting evaluation of that judgment to the Director. :)

# Issues status
https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+label%3Acss-counter-styles-3+

# Formal Objections
None

# Any changes in implementation information?
Chrome has implemented, in addition to Firefox

# Deadline for further comments
Don't care.

# Any changes in patent disclosures?
No

See [Requirements for updating a Candidate Recommendation Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot) for further information.

**Comment by xfq** [comment]
* i18n review: https://github.com/w3c/i18n-request/issues/157
* a11y review: https://github.com/w3c/a11y-request/issues/6

**Comment by plehegar** [comment]
* [Diff since last snapshot](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FCR-css-counter-styles-3-20171214%2F&doc2=https%3A%2F%2Fdrafts.csswg.org%2Fcss-counter-styles-3%2F)
* [commit history](https://github.com/w3c/csswg-drafts/commits/main/css-counter-styles-3/Overview.bs)
* there is one active [needs-resolution](https://www.w3.org/PM/horizontal/review.html?shortname=css-counter-styles). which i18n [hasn't closed yet (and probably should close)](https://github.com/w3c/i18n-activity/issues/42)
* [Normative references checker](https://labs.w3.org/normative-references/check?url=https%3A%2F%2Fdrafts.csswg.org%2Fcss-counter-styles-3%2F)
* no review request to [security](https://github.com/w3c/security-request/issues?q=is%3Aissue+counter) and [privacy](https://github.com/w3cping/privacy-request/issues?q=is%3Aissue+counter) folks? "[This specification introduces no new privacy or security considerations.](https://drafts.csswg.org/css-counter-styles-3/#priv-sec)"
* Deadline for comments should be at least 3 months (instead of the minimum) imho

**Comment by swickr** [comment]
Transition approved.

Please request security and privacy reviews before CR exit; those groups may make their own determinations as to the appropriate depth of their reviews.

**Comment by svgeesus** [comment]
[Published 27 July](https://www.w3.org/TR/2021/CR-css-counter-styles-3-20210727/)
