### ISSUE TITLE
FPNote for EPUB 3 Structural Semantics Vocabulary 1.1

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#387]
# Document title, URLs, estimated publication date

- EPUB 3 Structural Semantics Vocabulary 1.1
- https://www.w3.org/TR/2021/NOTE-epub-ssv-11-20211102/ a.k.a. https://www.w3.org/TR/epub-ssv-11/
- 2021-11-02

# Abstract

See https://www.w3.org/TR/2021/NOTE-epub-ssv-11-20211102/#abstract

# Status

See https://www.w3.org/TR/2021/NOTE-epub-ssv-11-20211102/#abstract

# Link to group's decision to request transition

https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-10-14-epub#resolution1

# Information about implementations known to the Group (if relevant)

"implementation" of a vocabulary is usage by users; it is scattered around publishers

**Comment by plehegar** [comment]
I'm rescinding the approval for this document. Since it will get published un Process 2021, considerations for [switching tracks](https://www.w3.org/2021/Process-20211102/#switching-tracks) needs to be taken into account.

**Comment by plehegar** [comment]
Process 2021 says:

1. A technical report that is or was a W3C Recommendation, W3C Statement, or Patent Review Draft cannot switch tracks.
2. A technical report should not switch away from the Recommendation Track without due consideration of the Patent Policy implications and approval of the W3C’s legal counsel if the Working Group envisions a likelihood of returning to it later.


1 doesn't apply since this content was never published in a Recommendation or a Patent Review Draft (a Candidate Recommendation Snapshot).

2 isn't a concern because the Working Group does not intend to bring it back to the Recommendation track in the future.

So, approved.

**Comment by iherman** [comment]
Document published at https://www.w3.org/TR/epub-ssv-11/, see also https://www.w3.org/blog/news/archives/9307. Closing.
