### ISSUE TITLE
First Note request for WebVMT: The Web Video Map Tracks Format

### ISSUE THREAD

**Issue by lvdbrink** [w3c/transitions#510]
# Document title, URLs, estimated publication date

- WebVMT: The Web Video Map Tracks Format
- https://w3c.github.io/sdw/proposals/geotagging/webvmt/
- 30-5-2023 (?)

# Abstract
This specification defines WebVMT, the Web Video Map Tracks format, which is an enabling technology whose main use is for marking up external metadata track resources in connection with the HTML <track> element. WebVMT files provide map presentation, annotation and interpolation synchronized to web media content, and more generally any form of data that is time-aligned with audio or video content, including those from location-aware devices such as dashcams, drones and smartphones.

# Status of the Document
Group Note

# Link to group's decision to request transition
https://lists.w3.org/Archives/Public/public-sdw-wg/2023May/0007.html

# Is it intended to be a W3C Statement?
No

**Comment by plehegar** [comment]
cc @bert-github

**Comment by plehegar** [comment]
This specification contains the definition of a format, which implies implementation requirements. The charter is clear this document is on the Note track but it seems to be an unfortunate oversight done in 2021. What was the rational for publishing this specification under the Note track instead of the REC track?

cc @bert-github @tidoust

**Comment by lvdbrink** [comment]
I would say we judged it to be still in incubation phase when we (re)chartered the SDWWG. Publication as a Note provides a ‘versioned' specification to encourage early adopters to implement a defined version of the format. More implementations will help engage and expand the online community to promote wider uptake and progress beyond the incubation phase towards a full standard.

**Comment by ogcscotts** [comment]
A major factor in the original plan to approach this work as a W3C Note / OGC Discussion Paper was that WebVMT as originally conceived had significant overlap with existing US Government Standards and there was concern that a new Recommendation / Standard would not be sufficiently different to be of value to the community. By publishing as a Note, the work would be widely available to people outside W3C and OGC who could assess the viability of the work before investing in a much more formal development process.

**Comment by rjksmith** [comment]
WebVMT uniquely allows timed video metadata to be shared in a format that is designed for the web and aligned with both [WICG DataCue](https://wicg.github.io/datacue/#datacue-interface) and [OGC standards](https://www.ogc.org/standards/). Rather than replacing existings standards, data can be exported in a common, accessible format which is agnostic of video encoding to enable search engines and web clients to access online details quickly, safely and simply.

User demand for geotagged video is being driven by affordable consumer products such as dash-cams, drones and body-cams, though these markets typically rely on proprietary formats. Community outreach activities are focussed on encouraging implementation of WebVMT export functions to enable user communities to control and share their own data online without requiring manufacturers to change their current sales strategies.

**Comment by lvdbrink** [comment]
In the interest of moving this forward, I'll add that since we are not chartered to publish this as a Rec, we want to move it forward as a Note for now. This was always the intention of the SDW group (as explained in comments above). We are not sure yet if we want to recharter. I request that we publish the document as a Note now, while we figure that out.

**Comment by plehegar** [comment]
We would be ok to publish it as a Note for now, with the following proposed sentence in the status of the document:
[[
This document is a Note, it has not been widely reviewed and should be considered as experimental only.  It may serve as the base for an upcoming W3C Recommendation.
]]

**Comment by lvdbrink** [comment]
Agreed! @rjksmith could you add that note to the Note please?

**Comment by rjksmith** [comment]
Excellent. I've added the suggested wording as requested in w3c/sdw#1433

**Comment by lvdbrink** [comment]
Great! @bert-github could you make sure it gets published?

**Comment by rjksmith** [comment]
Now online at https://www.w3.org/TR/webvmt/

Many thanks for all your help and support
