### ISSUE TITLE
First Draft Note request for W3C Vision

### ISSUE THREAD

**Issue by fantasai** [w3c/transitions#560]
# Document title, URLs, estimated publication date

Vision for W3C
https://www.w3.org/TR/w3c-vision/
https://github.com/w3c/AB-public/tree/main/Vision
Next publishing opportunity

Note: I don't know how to set up the draft to be served as HTML, but I guess if you download it locally it should work?

# Abstract

This Vision attempts to help world understand what W3C is, what it does and why that matters; and in particular to articulate the principles by which it operates and that guide its decisions.

# Status of the Document

See https://github.com/w3c/AB-public/tree/main/Vision#user-content-status-of-this-document

# Link to group's decision to request transition

https://www.w3.org/2023/03/16-ab-minutes.html#r05

# Is it intended to be a W3C Statement?

Yes

**Comment by ianbjacobs** [comment]
Hi all,

Thanks for working on this! I have a few comments and suggestions; I'm happy to do a pull request if that's appropriate. 

* "it must increase its respect". I don't think the Web has respect. Or, for that matter, ethical integrity. These are matters for human. What about something like "We will improve Web technology to foster people's trust in the platform." 
* Under "Vision for W3C" it says ""The fundamental purpose of the W3C ... provide an open forum." I don't think that's the fundamental purpose of W3C. The fundamental purpose is to work to ensure the long-term health and utility of the Web. I do think that the primary activity of the W3C is to provide an open forum. We also do (or have done) other things like develop software and tools, develop educational materials, and so on. 
* After talking about the fundamental purpose (or primary activity) there is a list, but no explanation for it. What about something like "To best carry out this activity:"
* The second bullet uses third person singular, all the other bullets use first person plural. 
* Under "Principles and Values": Instead of listing some principles for Web architecture here, could you instead refer to TAG documents (even if you name a few principles like decentralization while doing so)? That would shorten the intro and allow readers to more quickly reach the points about how the organization functions to achieve those architectural goals.
* There some redundancy between the elements of the list under Vision and the elements of the list under principles and values. For example, horizontal review is mentioned in both places. There may be reasons to put them in both places, but the characterization should be more distinct. For example, the vision could be inclusion of all users, regardless of ability (just as one example). And in the second list the characterization would be that we seek to create an accessible environment for collaboration, we conduct accesibility reviews of specifications as part of the standards process, and we develop guidelines to help developers create accessible Web sites. 

Lastly, a few years ago we worked with the IETF, ISOC, IAB, and IEEE to create a set of shared principles:
  https://open-stand.org/about-us/principles/

I would not expect these principles to be sufficient for a W3C vision document, but they might provide some inspiration, and ideally a W3C Vision document would remain consistent with the Open Stand Principles.

**Comment by frivoal** [comment]
@ianbjacobs Feedback on the content of the document is very much welcome, but the proper place for that would be in https://github.com/w3c/ab-public/, according to the work mode (lightly) documented at https://www.w3.org/wiki/AB/VisionTF

This is just a request to publish the existing content as a Draft Note, so that we can keep iterating on it, including addressing feedback like yours, all while publishing our work artifacts at a stable and archived URL, as required by https://www.w3.org/2023/Process-20230612/#report-stability

**Comment by ianbjacobs** [comment]
Added feedback here:
 https://github.com/w3c/AB-public/issues/104

**Comment by frivoal** [comment]
Thanks @ianbjacobs . Are you in charge of putting the draft note on TR as well?

**Comment by ianbjacobs** [comment]
Hi @frivoal,

I'm not aware that I am in charge of that, but if you need a staff member to do that, happy to help.

**Comment by plehegar** [comment]
Approved for publication.

**Comment by plehegar** [comment]
@frivoal , we didn't assign a proper team contact for publication. @ianbjacobs , if you're willing to do this, go for it. Otherwise I'll find someone else.

**Comment by plehegar** [comment]
One more note: use Process 2023 for the upcoming publication.

**Comment by ianbjacobs** [comment]
@plehegar, happy to help out. I assume next steps are to send a publication request to the Webmaster and install the document.

**Comment by ianbjacobs** [comment]
@fantasai,

Thank you for converting to bikeshed for publication. Would you mind re-running to get the new process template? (I tried to do bikeshed update locally but got a 404 on ttps://raw.githubusercontent.com/speced/bikeshed-data/master/data/ )

Thanks!

**Comment by ianbjacobs** [comment]
Thanks, #frivoal.

It looks like the change was merged yesterday:
 https://github.com/speced/bikeshed-boilerplate/pull/46

**Comment by ianbjacobs** [comment]
@frivoal, I made two additional tweaks to ensure the doc complies to pubrules:

* I moved the W3C style sheet for DNOTEs to the end of the head.
* The trailing slash on the AB home page link caused an error; I let the Webmaster know as I'm not sure if it's a tool issue or a data issue.

I will proceed with a publication request aiming for 25 July.

Ian

**Comment by frivoal** [comment]
> I moved the W3C style sheet for DNOTEs to the end of the head.

Is that required by Pubrules? Seems unnecessarily strict.

**Comment by ianbjacobs** [comment]
> Is that required by Pubrules?

Yes.

**Comment by ianbjacobs** [comment]
Hello all,

The document has been published:
   https://www.w3.org/TR/2023/DNOTE-w3c-vision-20230725/

Home page news:
 https://www.w3.org/news/2023/draft-note-vision-for-w3c/

**Comment by frivoal** [comment]
Thanks! Good to close.
