### ISSUE TITLE
First Note request for "VC Specifications Directory" - vc-specs-dir/

### ISSUE THREAD

**Issue by iherman** [w3c/transitions#586]
# Document title, URLs, estimated publication date

- title: VC Specifications Directory
- URL: https://www.w3.org/TR/2024/NOTE-vc-specs-dir-20240123/
- Latest editor's draft: https://w3c.github.io/vc-specs-dir/
- Estimated date of publication: 2024-01-23

# Abstract

This document serves as an unofficial directory for all known Verifiable Credential specifications whether they are released by a global standards setting organization, a community group, an open source project, or an individual.

# Status of the Document

See: https://www.w3.org/TR/2024/NOTE-vc-specs-dir-20240123/#sotd

# Link to group's decision to request transition

See https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-10-vcwg#resolution1

(Note that resolution talks about a publ date of Jan 30, but that is a small mistake, we decided to move it ahead.)

# Is it intended to be a W3C Statement?

No.

cc @msporny @brentzundel

**Comment by plehegar** [comment]
This document seems to contain a registry. Why is this publish on the Note track instead of the Registry track?

**Comment by iherman** [comment]
cc @msporny @brentzundel with the definitive answer.

**Comment by msporny** [comment]
> This document seems to contain a registry. Why is this publish on the Note track instead of the Registry track?

There are a number of WG members that would formally object if it we were to attempt to publish it as a W3C Registry.

The key concern among those WG members is that establishing a single point of truth for extensions to Verifiable Credentials (a registry) would undermine the decentralized nature of the solution. Because the core data model used by Verifiable Credentials (JSON-LD) enables decentralized extensibility, a centralized registry is not necessary to extend the data model.

At present, WG consensus is to publish "a collection of known extensions" (a directory) but not insist that the WG's list is the only list that could exist.

**Comment by plehegar** [comment]
Can we say in the SOTD that the document is not there to establish a former registry? If yes, I'm ok with moving forward.

**Comment by iherman** [comment]
s/former/formal/ ?

**Comment by plehegar** [comment]
> s/former/formal/ ?

indeed. "formal registry"

**Comment by msporny** [comment]
> Can we say in the SOTD that the document is not there to establish a formal registry?

Done in:

https://github.com/w3c/vc-specs-dir/commit/845d23f2e26bfcc8c41fa7cd1926a02a38c73918

**Comment by plehegar** [comment]
Approved

**Comment by iherman** [comment]
Published on 2024-02-01. Closing.
