### ISSUE TITLE
CR Request for Device Posture API - device-posture

### ISSUE THREAD

**Issue by himorin** [w3c/transitions#667]
# Document title, URLs, estimated publication date
Device Posture API
https://www.w3.org/TR/2024/WD-device-posture-20241115/
2024-11-26

<del>NOTE: this issue will be marked as transition review after [PR for changes section](https://github.com/w3c/device-posture/pull/164) merged</del> merged

# Abstract
https://www.w3.org/TR/2024/WD-device-posture-20241115/#abstract

# Status
https://www.w3.org/TR/2024/WD-device-posture-20241115/#sotd

# Link to group's decision to request transition
CfC: https://lists.w3.org/Archives/Public/public-device-apis/2024Nov/0000.html
resolution: https://lists.w3.org/Archives/Public/public-device-apis/2024Nov/0002.html

# Changes
https://www.w3.org/TR/2024/WD-device-posture-20241115/#substantive-changes-summary-fpwd

# Requirements satisfied
yes

# Dependencies met (or not)
dependencies unlikely to change

# Wide Review
- tracker: https://github.com/w3c/device-posture/issues/146
  - a11y: https://github.com/w3c/a11y-request/issues/84
  - tag: https://github.com/w3ctag/design-reviews/issues/575
    - delta: https://github.com/w3ctag/design-reviews/issues/689 , https://github.com/w3ctag/design-reviews/issues/690
  - i18n: https://github.com/w3c/i18n-request/issues/233
  - privacy: https://github.com/w3cping/privacy-request/issues/136
  - security: https://github.com/w3c/security-request/issues/69

# Issues addressed
https://github.com/w3c/device-posture/issues?q=is%3Aissue+is%3Aclosed

# Formal Objections
no

# Implementation
will be prepared from https://wpt.fyi/results/device-posture

# Patent disclosures
https://www.w3.org/groups/wg/das/ipr/

/cc @diekus @kenchris @darktears @anssiko @reillyeon

**Comment by himorin** [comment]
updated URL following PR (on changes section) merged.
would take some time (on r?) for html tidyup for actual publication.

**Comment by darktears** [comment]
@plehegar yes it was. We went through PING review. I don't want to discuss again what was discussed before (see PING minutes) but long story short, there isn't a mechanism existing in the web platform to guard CSS API (specifically CSS MQs) behind a permission policy so adding permission policy would only apply to the JS surface. PING and CSS WGs have started a discussion around that (which has been silent so far). At the end it was deemed that the fingerprinting is very low risk provided it doesn't expose much information useful to bad actors and is getting less and less relevant as more devices hit the market.

**Comment by darktears** [comment]
I did not request another TAG look on this specific section. When TAG reviewed this specification there were never plans to add a permission policy in the first place. This specific section was documented to be concise about the problem space that's really it.

FWIW this API just shipped in Chromium.

**Comment by simoneonofri** [comment]
hi @plehegar, thank you for the pointer.

@darktears i am reading the spec.

**Comment by simoneonofri** [comment]
Since the API only provides information, the security part is assimilated to privacy concerns (it should also be nice to reference fingerprinting here).

I am specifically reasoning about [this message](https://github.com/w3c/device-posture/issues/111#issuecomment-2396904450) concerning possible abuse cases (e.g., how this can be abused by aggressive advertising? or for XS-leaks).

No further issues for now.

**Comment by darktears** [comment]
Thanks @simoneonofri for taking a look.

We do cover fingerprinting over [here](https://www.w3.org/TR/device-posture/#identifying-users-across-contexts).

There isn't much value in the API for abuse by advertisers. If the intention is to detect a foldable device there are many other ways to detect them without that API. If it's to track them across contexts again it's only possible to potentially track a user which is using the 'folded' posture (any other devices will return continuous and non folded foldable devices as well) but it will all fall apart if the posture changes (which is user triggered). Also many many devices are shipping now so folded devices are getting more and more common.

We do want to expose the API to iframes because there are legit use cases for it (as some developers commented).

**Comment by simoneonofri** [comment]
@darktears, you're welcome.

Could you put in the Security Considerations Section the reference to that point already mentioned in the privacy considerations?

Another Threat Actor we can consider is someone who places in the iframe something like [BeEF](https://github.com/beefproject/beef) - back in the day, I tended to put it inside an `iframe` :).

**Comment by darktears** [comment]
I could add the reference but I'm not sure it provides any value provided that the Security Considerations Section is right above the Privacy section and the first paragraph is what we're talking about, no-scrolling required pretty much.

**Comment by plehegar** [comment]
Approved.

Thank you @simoneonofri and @darktears .

**Comment by darktears** [comment]
Thanks @plehegar for the approval.
